sudo:
    - false

language:
    - cpp

compiler:
    - gcc
    - clang

install:
  - export CXX="g++-4.8" CC="gcc-4.8"

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang

script:
    mkdir build && cd build && cmake .. && make

notifications:
    recipients:
        - fabian.reister92@gmail.com
    email:
        on_success: always
        on_failure: always

os:
    - linux
